### ISSUE TITLE
Add gir1.2-udisks-2.0 to depends

### ISSUE THREAD

**Issue by HateBreed** [SolydXK/solydxk-system#1]
Does not run without gir1.2-udisks-2.0

To test this:
Remove gir1.2-udisks-2.0 <code>$ sudo apt-get remove gir1.2-udisks-2.0</code>

Run: <code>$ sudo solydxk-system </code>

Result: <code>Traceback (most recent call last):
  File "/usr/lib/solydxk/system/main.py", line 12, in <module>
    from solydxk_system import SolydXKSystemSettings
  File "/usr/lib/solydxk/system/solydxk_system.py", line 13, in <module>
    from udisks2 import Udisks2
  File "/usr/lib/solydxk/system/udisks2.py", line 8, in <module>
    gi.require_version('UDisks', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace UDisks not available
</code>

Install gir1.2-udisks-2.0 <code>$ sudo apt-get install gir1.2-udisks-2.0</code>

And success.

**Comment by HateBreed** [comment]
In https://github.com/SolydXK/solydxk-system/commit/2dedbf3e80826c1269c140866a582a08eb121144 the dependency was added. Solved and closed.
